beltei/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.apps import apps
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.conf.urls.i18n import i18n_patterns

from django.utils.translation import gettext_lazy as _ 
"""
    Check data for uploading
"""
from django.conf import settings 
from django.conf.urls.static import static 

app_name = 'Beltei'
admin.site.site_header = "Beltei Admin"
admin.site.site_title = "Beltei Admin Portal"
admin.site.index_title = "Welcome to beltei student portal"

# urlpatterns = [
# 	path('i18n/', include('django.conf.urls.i18n')),
# 	path('admin/', admin.site.urls),
# 	path('', include('students.urls')),
# ]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
	path('admin/', admin.site.urls),
	path('', include('students.urls')),
	prefix_default_language = True, 
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainview/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'mainview'
urlpatterns = [
  
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

from .views import SearchStudentView


app_name = 'students'


urlpatterns = [
	path('search/', SearchStudentView.as_view(), name='student_search'),

    url(r'^$', views.IndexView.as_view(), name='index_view'),    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainview/models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import date
from django.conf import settings
import os
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

GENDER = (
    ('Male', 'M'),
    ('Female', 'F'),
)


def upload_location(instance, filename):
    filebase, extension = filename.split(".")
    return "%s/%s.%s" %(instance.id, instance.id, extension)

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.png', '.jpg', '.jpeg']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')



def user_directory_path(request, filename):
	# return "files/users/%s/%s" % (request.user.id, filename)
    return '/'.join(['content', request.student_id, filename])



def increment_student_id():
    last_student = Student.objects.all().order_by('id').last()
    if not last_student:
        return 'BLT00001'
    width = 5
    student_number = last_student.student_id
    student_int = int(student_number.split('BLT')[-1])
    new_student_int = student_int + 1
    formatted = (width - len(str(new_student_int))) * "0" + str(new_student_int)
    new_student_int = 'BLT' + str(formatted)
    return str(new_student_int)


# def increment_student_id():
# 	last_student = Student.objects.all().order_by('id').last()
# 	if not last_product:
# 		return 'BLT00001'
# 	width = 5
# 	product_number = last_student.product_number
# 	product_int = int(product_number.split('BLT')[-1])
# 	new_product_int = product_int + 1
# 	formatted = (width - len(str(new_product_int))) * "0" + str(new_product_int)
# 	new_product_int = 'BLT' + str 


class Student(models.Model): 
    student_id = models.CharField(max_length=500, null=True, blank=True, 
        validators=[RegexValidator(regex='^[a-zA-Z0-9]*$',
        message='Produce number must be Alphanumeric',code='Number is invalide'),], 
        default=increment_student_id)
    first_name_en = models.CharField(max_length=255)
    first_name_kh = models.CharField(max_length=255)
    last_name_en = models.CharField(max_length=255)
    last_name_kh = models.CharField(max_length=255)
    gender = models.CharField(max_length=20, choices=GENDER)
    nationality_en = models.CharField(max_length=30)
    nationality_kh = models.CharField(max_length=30)
    image = models.FileField(blank=True, upload_to=user_directory_path,  validators=[validate_file_extension])
    certificate = models.FileField(blank=True, upload_to=user_directory_path,  validators=[validate_file_extension])
    description_en = models.TextField() 
    description_kh = models.TextField() 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    is_status = models.BooleanField(default=True)
    def __str__ (self):
    	# return self.name + ' ' + str(self.created_at)
    	return str(self.first_name_en) +' ' + str(self.last_name_en)
    class  Meta:
    	ordering = ['-created_at']

mainview/views.py
from django.shortcuts import render

# Create your views here.

students/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404, render_to_response
from django.http import HttpResponse
from django.template import loader 
from django.views import generic
from django.urls import reverse_lazy

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from django.views.generic import View, TemplateView 
from .models import Student
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.template import loader 
from django.views.generic.list import ListView
from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator

from django.utils import translation
from django.utils.translation import gettext as _
from django.utils.translation import activate, get_language_info


class IndexView(SuccessMessageMixin, generic.ListView):
	template_name =  'student/index.html'
	context_object_name = 'all_student'
	paginate_by = 5

	def get_queryset(self):
		# user_language = 'km'
		# translation.activate(user_language)
		# self.request.session[translation.LANGUAGE_SESSION_KEY] = user_language
		if translation.LANGUAGE_SESSION_KEY in self.request.session: 
			del self.request.session[translation.LANGUAGE_SESSION_KEY]
		return Student.objects.filter(is_status=True).order_by('-created_at')


class SearchStudentView(ListView):

	model = Student
	template_name = 'student/result_search.html'
	paginate_by = 5

	context = {
		'hello' : _('hello')
	}

	def get(self, request): 
		q = request.GET['q']
		data = Student.objects.filter(student_id=q.strip(), is_status=True) | Student.objects.filter(first_name_en__contains = q.strip(), is_status=True) | Student.objects.filter(last_name_kh__contains = q.strip(), is_status=True)| Student.objects.filter(last_name_en__contains = q.strip(), is_status=True)| Student.objects.filter(nationality_en__contains=q.strip(), is_status=True)| Student.objects.filter(nationality_kh__contains=q.strip(), is_status=True) | Student.objects.filter(first_name_kh__contains = q.strip(), is_status=True)
		return render(request, self.template_name, {'all_student':data, 'title':q, 'hello': _('Hello')})

mainview/templates/mainview/default.html
{% extends 'product/base.html' %}

{% block title %} Dashboard {% endblock %}

{% block body %}

	<div>
		<div class="home_title">
			<p> <span class="glyphicon glyphicon-th-large">  </span> Dashboard </p>
		</div>
		<div class="home_menu">
			<div class="row" style="margin-top: 20px;">

				<!-- Block user -->
				<div class="col-xs-6 col-sm-4 col-md-3">
					<div class="home_box_user">
						<div class="home_user">
							
							<div class="default_item_left">
								<span class="glyphicon glyphicon-user default_item_left_icon" ></span>
							</div>
							<div class= "default_item_right">
								{% if count_user > 1 %}
									<p> {{ count_user }} </p>
									<p> Users </p>
								{% else %}
									<p> {{ count_user }} </p>
									<p> User </p>
								{% endif %}
							</div>

						</div>
						<div class="home_box_detail">
							<a href="{% url 'usercontrol:listuser' %}">
								<table style="width: 100%;">
									<tr>
										<td>View detail</td>
										<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
									</tr>
								</table>
							</a>
						</div>
					</div>
				</div>



				<!-- Block customer -->
				<div class="col-xs-6 col-sm-4 col-md-3 ">
					<div class="home_box_customer">
						<div class="home_customer">
							<div class="default_item_left">
								<span class="glyphicon glyphicon-user default_item_left_icon" ></span>
							</div>
							<div class= "default_item_right">
								{% if count_customer > 1 %}
									<p> {{ count_customer }} </p>
									<p> Customers </p>
								{% else %}
									<p> {{ count_customer }} </p>
									<p> Customer </p>
								{% endif %}
							</div>
						</div>



						<div class="home_box_detail">

							{% if count_customer > 0 %}
								<a href="{% url 'customer:customer_index' %}">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% else %}
								<a href="#">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% endif %}



						</div>
					</div>
				</div>

				
				<!-- Block category -->
				
				<div class="col-xs-6 col-sm-4 col-md-3">
					<div class="home_box_category">
						<div class="home_category">
							
							<div class="default_item_left">
								<span class="glyphicon glyphicon-user default_item_left_icon" ></span>
							</div>

							<div class= "default_item_right">
								{% if count_product_category > 1 %}
									<p> {{ count_product_category }} </p>
									<p> Categories </p>
								{% else %}
									<p> {{ count_product_category }} </p>
									<p> Category </p>
								{% endif %}
							</div>


						</div>
						<div class="home_box_detail">
							
							{% if count_product_category > 0 %}
								<a href="{% url 'product:category_list' %}">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% else %}
								<a href="#">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% endif %}

						</div>
					</div>
				</div>



				<!-- Block promotion -->
				<div class="col-xs-6 col-sm-4 col-md-3">
					<div class="home_box_promotion">
						<div class="home_promotion">
							<div class="default_item_left">
								<span class="glyphicon glyphicon-user default_item_left_icon" ></span>
							</div>
							<div class= "default_item_right">
								{% if count_promotion > 1 %}
									<p> {{ count_promotion }} </p>
									<p> Promotions </p>
								{% else %}
									<p> {{ count_promotion }} </p>
									<p> Promotion </p>
								{% endif %}
							</div>
						</div>
						<div class="home_box_detail">
							<a href="#">
								<table style="width: 100%;">
									<tr>
										<td>View detail</td>
										<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
									</tr>
								</table>
							</a>
						</div>
					</div>
				</div>





			</div>
		</div>
	</div>

{% endblock %}

mainview/templates/product/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	{% block head %}{% endblock %}

    <!-- Latest compiled and minified CSS -->
	<!-- /<script  type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"> </script> -->
    <!-- <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}" charset="UTF-8"></script>
	<script type="text/javascript" src="{% static 'js/locales/bootstrap-datetimepicker.en.js' %}" charset="UTF-8"></script>
	<link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
	<script  type="text/javascript" src="{% static 'js/rate.js' %}"> </script>
	<script  type="text/javascript" src="{% static 'js/slidebar.js' %}"> </script>
	<link rel="stylesheet"  href="{% static 'css/main.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/style.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/krotis.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/pralis.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/login.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/product.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/rate.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/slidebar.css' %}">
	<link rel="stylesheet"  href="{% static 'css/homepage.css' %}">
	<link rel="stylesheet"  href="{% static 'css/stock.css' %}">
	<link rel="stylesheet"  href="{% static 'css/user.css' %}">
	<link rel="stylesheet"  href="{% static 'css/category.css' %}">
	<link rel="stylesheet"  href="{% static 'css/sell.css' %}">
	<link rel="stylesheet"  href="{% static 'css/client.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body style="background-color: #f1f1f1;">
	<div>
		<header class="bs-docs-nav navbar navbar-static-top my_header" id="top"> 
			<div class="container"> 
				<div class="navbar-header" style="color: white;"> 
					<button aria-controls="bs-navbar" aria-expanded="false" class="collapsed navbar-toggle" data-target="#bs-navbar" data-toggle="collapse" type="button" style="color:white !important; font-size: 13.5px; border: 1px solid white !important;"> 
						<span class="glyphicon glyphicon-menu-hamburger"></span>
					</button> 
				    <a class="navbar-brand" href="" style="font-weight: bold;"> BELTEI </a>
				</div> 

				<nav class="collapse navbar-collapse" id="bs-navbar">
					<ul class="nav navbar-nav navbar-left">
						<li class="">
							<a class="" href=""><span class="glyphicon glyphicon-th"></span> Student </a>
						</li>
					</ul>
				
					<!-- {% get_current_language as LANGUAGE_CODE %} -->
					{% get_current_language as LANGUAGE_CODE %}
					<ul class="nav navbar-nav navbar-right" style="margin-right: 0px !important;">
						<!-- set_language is a default method of Django -->
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input type="hidden" name="text" value="{{ redirect_to }}">
							<select name="language" id="">
								{% get_available_languages as LANGUAGES %}
								{% get_language_info_list for LANGUAGES as languages %}
								{% for language in languages %}
									<option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}/> 
										{{ language.name_locale }} ({{ language.code }})
									</option>
								{% endfor %}
							</select>
							<input type="submit" value="Go"/>
							
						</form>
					</ul>
					<!-- <ul class="nav navbar-nav navbar-right" style="margin-right: 0px !important;">
						{% get_current_language as LANGUAGE_CODE %}
						<li> <a href=""> {{ LANGUAGE_CODE }} </a> </li>
					</ul> -->
				</nav> 
			</div> 

		</header>

		{% block search %}

			<div style="width:100%; padding-top:5px; padding-bottom: 5px; background-color: black;">
				<div class="container bs-docs-container">
					
					<form class="form-inline" action="{% url 'students:student_search' %}"  method="get">
						{% csrf_token %}
						<div class="form-group">
							<div class="input-group">
						    	<div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
						    	<input style="" type="text" class="form-control form-control-sm ml-3 w-75" name= "q" value="" placeholder="Search student" required="">		
						    </div>
					  	</div>

					</form>
				</div>
			</div>

		{% endblock %}

		<main class="bd-content p-5" id="content" role="main">
			
			<div style="background-color: #f1f1f1;">

				<div class="container bs-docs-container" style="min-height: 690px; height: auto;">
					
					<div style="background-color: white; padding-left: 10px; padding-right: 10px; padding-top: 10px;">
						{% block body %}

						{% endblock %}
					</div>
				</div>
			<div>
		</main>

		<footer>
			<div class="bs-docs-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4" style="text-align: center;">
							<h4>Follow Us: </h4>
						    {% if all_media %}
						    	<ul class="bs-docs-footer-links">
									{% for i in all_media %}
										<li>
											<a href="{{ i.url }}" target="_blank">
												<img src = "../../../{{ i.logo.url }}" style="width: 40px; height: 40px;">
											</a>
										</li>
									{% endfor %}
								</ul>

							{% endif %}
						</div>
						<div class="col-md-4" style="text-align: center;">
							<h4>Contact Us:</h4>
							<p><span class="glyphicon glyphicon-envelope"> </span> Email: Beltei@gmail.com</p>
							<p><span class="glyphicon glyphicon-earphone"></span> Tel: (855)12-345-678</p>
							
						</div>
						<div class="col-md-4" style="text-align: center; !important;">
							<h4>Address: </h4>
							<p>Beltei univeristy</p>
							<span style="font-size: 10px;">Phnom Penh</span>
						</div>
					</div>
				</div>
			</div>



			<div style="width: 100%; height: 50px; background-color: #252525;">
				<div class="container">
					<div class="row" style="padding-top: 20px;">
						<div class="col-md-12" style="text-align: center; color:white;">
							<p>Copyright ©2020 Ai Cambodia. Tel: (+855)93-524-860</p>
						</div>
					</div>
				</div>
			</div>
		</footer>

		{% block javascript %}
			
		{% endblock %}
	</div>
</body>
</html>

mainview/templates/product/success_save.html
{% extends 'product/base.html' %}

{% block title %} Product {% endblock %}

{% block body %}

	<div class="index_background">
		<div class="head_index">
			<h5>Order successfully.</h5>
		</div>
	</div>

{% endblock %}

mainview/templates/student/index.html
{% extends 'product/base.html' %}

{% load i18n %}

{% block title %} Student profiel {% endblock %}



{% block body %}

	<div style="padding-bottom: 10px;">

		{% if all_student %}

			<h1> {% trans "Student list" %} </h1>

			<table class="table">

				<thead>
					<tr>
						<th>{% trans "ID" %}</th>
						<th>{% trans "First Name" %}</th>
						<th>{% trans "Last Name" %}</th>
						<th>{% trans "Sex" %}</th>
						<th>{% trans "Nationality" %}</th>
						<th>{% trans "Photo" %}</th>
						<th>{% trans "Certificate" %}</th>
					</tr>
				</thead>

				<tbody>
					
					{% get_current_language as LANGUAGE_CODE %}
					{% if LANGUAGE_CODE == 'km' %}
						{% for student in all_student %}
							<tr>
								<td><p>{{ student.student_id }}</p></td>
								<td><p>{{ student.first_name_kh }}</p></td>
								<td><p>{{ student.last_name_kh }}</p></td>
								<td><p>{% trans student.gender %}</p></td>
								<td><p>{{ student.nationality_kh }}</p></td>
								<td><img src = "../../../{{ student.image.url }}" style="width:55px; height: 60px;"></td>
								<td><img src = "../../../{{ student.certificate.url }}" style="width:55px; height: 60px;"></td>
							</tr>
						{% endfor %}
					{% else %}
						{% for student in all_student %}
							<tr>
								<td><p>{{ student.student_id }}</p></td>
								<td><p>{{ student.first_name_en }}</p></td>
								<td><p>{{ student.last_name_en }}</p></td>
								<td><p>{{ student.gender }}</p></td>
								<td><p>{{ student.nationality_en }}</p></td>
								<td><img src = "../../../{{ student.image.url }}" style="width:55px; height: 60px;"></td>
								<td><img src = "../../../{{ student.certificate.url }}" style="width:55px; height: 60px;"></td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
				
			</table>

			<div class="pagination_index">
					
				{% if is_paginated %}
				<hr>
					<ul class="pagination" style="margin:0px 0px !important">
					{% if page_obj.has_previous %}
					    <li>
					        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
					    </li>
					{% endif %}
					    <li class="">
					        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
					    </li>
					{% if page_obj.has_next %}
					    <li>
					        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
					    </li>
					{% endif %}
					</ul>
				
				{% endif %}
			</div>
		{% else %}
			<h1>No student.</h1>
		{% endif %}


	</div>
	
{% endblock %}

mainview/templates/student/result_search.html
{% extends 'product/base.html' %}

{% load i18n %}

{% block title %} Result search {% endblock %}

{% block body %}

	<div class="index_background">

	<!-- 	{{ hello }}
		{% trans "translate search" %}  -->

		{% if all_student %}

			{% if all_student.count > 1 %}
				<div style="padding-top: 20px;">
					<p class="search_title">{% trans "Results search of" %} "<span style="font-style: italic;">{{ title }}" </span>:</p>
					<hr style="border-bottom: 1px solid gray;" />
				</div>
			{% else %}
				<div style="padding-top: 20px;">
					<p class="search_title">{% trans "Result search of" %} "<span style="font-style: italic;">{{ title }}" </span>:</p>
					<hr style="border-bottom: 1px solid gray;" />
				</div>
			{% endif %}
			

			<table class="table">
				<thead>
					<tr>
						<th>{% trans "ID" %}</th>
						<th>{% trans "First Name" %}</th>
						<th>{% trans "Last Name" %}</th>
						<th>{% trans "Sex" %}</th>
						<th>{% trans "Nationality" %}</th>
						<th>{% trans "Photo" %}</th>
						<th>{% trans "Certificate" %}</th>
					</tr>
				</thead>
				<tbody>
					{% get_current_language as LANGUAGE_CODE %}
					{% if LANGUAGE_CODE == 'km' %}
						{% for student in all_student %}
							<tr>
								<td><p>{{ student.student_id }}</p></td>
								<td><p>{{ student.first_name_kh }}</p></td>
								<td><p>{{ student.last_name_kh }}</p></td>
								<td><p>{% trans student.gender %}</p></td>
								<td><p>{{ student.nationality_kh }}</p></td>
								<td><img src = "../../../{{ student.image.url }}" style="width:55px; height: 60px;"></td>
								<td><img src = "../../../{{ student.certificate.url }}" style="width:55px; height: 60px;"></td>
							</tr>
						{% endfor %}
					{% else %}
						{% for student in all_student %}
							<tr>
								<td><p>{{ student.student_id }}</p></td>
								<td><p>{{ student.first_name_en }}</p></td>
								<td><p>{{ student.last_name_en }}</p></td>
								<td><p>{{ student.gender }}</p></td>
								<td><p>{{ student.nationality_en }}</p></td>
								<td><img src = "../../../{{ student.image.url }}" style="width:55px; height: 60px;"></td>
								<td><img src = "../../../{{ student.certificate.url }}" style="width:55px; height: 60px;"></td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
				
			</table>

			<div class="pagination_index">
					
				{% if is_paginated %}
				<hr>
					<ul class="pagination" style="margin:0px 0px !important">
					{% if page_obj.has_previous %}
					    <li>
					        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
					    </li>
					{% endif %}
					    <li class="">
					        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
					    </li>
					{% if page_obj.has_next %}
					    <li>
					        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
					    </li>
					{% endif %}
					</ul>
				
				{% endif %}
			</div>

		{% else %}
			<h1>No student.</h1>
		{% endif %}
		
	</div>

	<!-- <div class="pagination_index">
				
		{% if is_paginated %}
		<hr>
			<ul class="pagination" style="margin:0px 0px !important">
			{% if page_obj.has_previous %}
			    <li>
			        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
			    </li>
			{% endif %}
			    <li class="">
			        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
			    </li>
			{% if page_obj.has_next %}
			    <li>
			        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
			    </li>
			{% endif %}
			</ul>
		
		{% endif %}
	</div> -->


{% endblock %}